version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    depends_on:
      - rabbitmq
      - wiki

  wiki:
    build: 
      context: ./wiki_processor
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
